name    'puppet-gdash'
version '0.0.0'
source 'https://github.com/seattle-biomed/puppet-gdash'
author 'Seattle Biomedical Research Institute'
license 'MIT'
summary 'Install and manage Gdash'
description 'Install and manage Gdash, a dashboard for Graphite'
project_page 'https://github.com/puppet/puppet-gdash'

dependency 'puppetlabs/vcsrepo', '>= 0.2.0'
dependency 'ploperations/bundler', '>= 1.0.0'
dependency 'puppetlabs/ruby', '>= 0.1.0'
